version: '3.8'
services:
  backend:
    env_file:
      - backend/.env
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "127.0.0.1:8001:8001"
    expose:
      - 8001
    depends_on:
      - database

  frontend:
    env_file:
      - frontend/.env
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3006:3006"
    expose:
      - 3006
  database:
    image: postgres:13.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ProjectWebsite
    ports:
      - "5432:5432"
