# Enable specific rule files
app-layer-events.rules
decoder-events.rules
dhcp-events.rules
dns-events.rules
http-events.rules
ipsec-events.rules
kerberos-events.rules
nfs-events.rules
ntp-events.rules
smb-events.rules
smtp-events.rules
stream-events.rules
tls-events.rules
ftp-events.rules
ssh-events.rules
http-events.rules

# Enable ET categories
emerging-attack_response.rules
emerging-exploit.rules
emerging-malware.rules
emerging-scan.rules
emerging-web_client.rules
emerging-web_server.rules
emerging-web_specific_apps.rules
emerging-sql.rules
emerging-trojan.rules
emerging-dos.rules
emerging-current_events.rules
emerging-user_agents.rules
emerging-shellcode.rules
emerging-icmp.rules
emerging-ftp.rules
emerging-info.rules
emerging-misc.rules
emerging-policy.rules
emerging-backdoor.rules
emerging-botcc.rules
emerging-hunting.rules
