input {
  beats {
    port => 5044
  }
}

filter {
  # Add this at the beginning to see what fields are coming in
  mutate {
    add_field => { "debug_logtype" => "%{[fields][log_type]}" }
  }

  if [fields][log_type] == "apache" {
    grok {
      match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
    }
    mutate {
      remove_field => [ "timestamp" ]
      add_field => { "processed_by" => "apache_filter" }
    }
  }
  
  else if [fields][log_type] == "snort_csv" {
    csv {
      separator => ","
      skip_empty_columns => true
      columns => [ "timestamp", "pkt_num", "proto", "pkt_gen", "pkt_len", "dir", "src_ap", "dst_ap", "rule", "action", "msg", "class"]
    }
    mutate {
      convert => {
          "pkt_num" => "integer"
          "pkt_len" => "integer"
          "priority" => "integer"
          "sid" => "integer"
          "rev" => "integer"
        }
      add_field => { "processed_by" => "snort_filter" }
    }
    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
  }
else if [fields][log_type] == "snort_alert" {
    grok {
      match => { "message" => "%{DATA:timestamp} \[%{INT:gid}:%{INT:sid}:%{INT:rev}\] %{DATA:alert} \[Classification: %{DATA:classification}\] \[Priority: %{INT:priority}\] {%{DATA:protocol}} %{IP:src_ip}:%{INT:src_port} -> %{IP:dest_ip}:%{INT:dest_port}" }
    }
    
    date {
      match => [ "timestamp", "MM/dd-HH:mm:ss.SSSSSS" ]
      target => "@timestamp"
    }
    
    mutate {
      convert => {
        "priority" => "integer"
        "sid" => "integer"
        "rev" => "integer"
        "gid" => "integer"
        "src_port" => "integer"
        "dest_port" => "integer"
      }
      add_field => { "processed_by" => "snort_alert_filter" }
    }
  }  
  # If neither condition matched, add a debug field
  else {
    mutate {
      add_field => { "processed_by" => "no_matching_filter" }
    }
  }
}

output {
  if [processed_by] == "apache_filter" {
    elasticsearch {
      hosts => ["http://127.0.0.1:9200"]
      index => "apache-%{+YYYY.MM.dd}"
      data_stream => false
    }
    stdout { codec => rubydebug }
  }
  
  else if [processed_by] == "snort_filter" {
    elasticsearch {
      hosts => ["http://localhost:9200"]
      index => "snort-logs-%{+YYYY.MM.dd}"
      data_stream => false
    }
    stdout { codec => rubydebug }
  }
  else if [processed_by] == "snort_alert_filter" {
    elasticsearch {
      hosts => ["http://localhost:9200"]
      index => "snort-alerts-%{+YYYY.MM.dd}"
      data_stream => false
    }
    stdout { codec => rubydebug }
  }
  # Debug output for events that didn't match any condition
  else {
    elasticsearch {
      hosts => ["http://127.0.0.1:9200"]
      index => "debug-logs-%{+YYYY.MM.dd}"
      data_stream => false
    }
    stdout { codec => rubydebug }
  }
}
